### PR TITLE
Sequel 5

### PR DESCRIPTION
**Pull request by uhoh-itsmaciek**
@fdr this updates the Travis config (and I had to re-run `bundle install`; not sure why) so the tests pass. I don't mind just not supporting older Sequel versions and push this under a major version bump.

### CODE REVIEW

**Comment by fdr** [comment]
should I do anything with this PR, e.g. use it, or are you JustGunnaMergeIt or...

**Comment by uhoh-itsmaciek** [comment]
I guess I'll just merge it. Was wondering if you had comments on the `bundle install` that I had to do to update the Gemfile.lock but whatevs.

**Comment by uhoh-itsmaciek** [comment]
Merged and pushed 2.0.0 to Rubygems.

**Comment by fdr** [comment]
Ah. NFI on `bundle install`. Welp, guess I'll unpin the git version then. Thanks for making things easy.

**Pull request merged**
