### PR TITLE
Ruby 2.7 updates

### PR DESCRIPTION
**Pull request by beanieboi**
Hi 👋 

attr_vault is a great library and I wanted it to be compatible with Ruby 2.7. there were only minor things to change in order to make it work with Ruby 2.7

- upgrade Sequel, because of the changes to BigDecimal in Ruby 2.7, we need to use a newer version of Sequel
- fixes some keyword arguments to fix some warnings in Ruby 2.7

let me know what you think

### CODE REVIEW

**Comment by uhoh-itsmaciek** [comment]
Thanks, Ben! Looks great.

**Comment by beanieboi** [comment]
awesome, thanks for merging. would you mind cutting a new release for the recent changes on master?

**Comment by uhoh-itsmaciek** [comment]
Hmm, looks like there's an issue with Travis. Let me try moving to GitHub Actions--something I've been meaning to do anyway--and I'll cut a release after CI passes.

**Comment by beanieboi** [comment]
Thank you!

**Comment by msakrejda** [comment]
https://rubygems.org/gems/attr_vault/versions/2.1.2

**Pull request merged**
